### ISSUE TITLE
can't resolve 'brace' in /node-modules/react-ace-editor/dist

### ISSUE THREAD

**Issue by ssadler9** [chunsli/react-ace-editor#1]
I just downloaded and installed the npm package for a React project I'm building.  The code currently isn't working because 'brace' cannot be resolved.  Looking into the dist folder, this appears to be a path issue.  How do I get around this error?

**Comment by CBernsCode** [comment]
Having the same issue over here.

**Comment by dobre-robert-marius** [comment]
`npm install brace` did the job for me.
